trigger:
- main

jobs:
  - job: Build
    displayName: "Build"
    pool:
      name: Azure Pipelines
      vmImage: "windows-2019"
      demands: npm
    
    steps:
      

      - task: DotNetCoreCLI@2
        displayName: Restore
        inputs:
          command: restore
          projects: '**/**/*.csproj'
      
      - task: DotNetCoreCLI@2
        displayName: Build
        inputs:
          projects: '**/**/*.csproj'
          arguments: '--configuration Release'
      
      - task: DotNetCoreCLI@2
        displayName: Publish
        inputs:
          command: publish
          publishWebProjects: false
          projects: '**/**/*.csproj'
          arguments: '--configuration Release --output $(Build.ArtifactStagingDirectory)'
          zipAfterPublish: true

      - task: NodeTool@0
        inputs:
          versionSpec: '10.x'
          
      - task: TfxInstaller@3
        inputs:
          version: 'v0.9.x'
      - task: PackageAzureDevOpsExtension@3
        inputs:
          rootFolder: '$(Build.SourcesDirectory)'
          outputPath: '$(Build.ArtifactStagingDirectory)'
          publisherId: 'dimaros'
          updateTasksVersion: true
          extensionVisibility: 'private'
          extensionPricing: 'free'
          zipAfterPublish: true

      - task: PublishBuildArtifacts@1
        displayName: "Publish Artifact"
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        condition: succeededOrFailed()