trigger:
- main

jobs:
  - job: Build
    displayName: "Build"
    pool:
      name: Azure Pipelines
      vmImage: "windows-2019"
    
    steps:

      - task: DotNetCoreCLI@2
        displayName: Restore
        inputs:
          command: restore
          projects: '**/**/*.csproj'
      
      - task: DotNetCoreCLI@2
        displayName: Build
        inputs:
          projects: '**/**/*.csproj'
          arguments: '--configuration Release'
      
      - task: DotNetCoreCLI@2
        displayName: Publish
        inputs:
          command: publish
          publishWebProjects: false
          projects: 'Release'
          arguments: '--configuration Release --output $(Build.artifactstagingdirectory)'
          zipAfterPublish: true
      
      - task: PackageAzureDevOpsExtension@3
        inputs:
          rootFolder: '$(Build.SourcesDirectory)'
          outputPath: '$(Build.ArtifactStagingDirectory)\vsts-developer-tools-build-tasks.vsix'
          updateTasksVersion: true

      
