name: '1.0$(Rev:.r)'

trigger:
- main

stages:
- stage: 'Build'
  displayName: 'Build'
  jobs:
  - job: Build
    displayName: "Build"
    pool:
      name: Azure Pipelines
      vmImage: "windows-2019"
      demands: npm
    
    steps:
      - task: DotNetCoreCLI@2
        displayName: Restore
        inputs:
          command: restore
          projects: '**/**/*.csproj'
      
      - task: DotNetCoreCLI@2
        displayName: Build
        inputs:
          projects: '**/**/*.csproj'
          arguments: '--configuration Release'

      - task: NodeTool@0
        inputs:
          versionSpec: '10.x'
          
      - task: TfxInstaller@3
        inputs:
          version: 'v0.9.x'
      - task: PackageAzureDevOpsExtension@3
        inputs:
          rootFolder: '$(Build.SourcesDirectory)'
          outputPath: '$(Build.ArtifactStagingDirectory)'
          publisherId: 'dimaros'
          updateTasksVersion: true
          extensionVisibility: 'private'
          extensionPricing: 'free'
          extensionVersion: '$(Build.BuildNumber)'
        
      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)'
          ArtifactName: 'vsix'
        condition: succeededOrFailed()

- stage: 'Test'
  displayName: 'Testing'
  dependsOn: 'Build'
  jobs:
  - job:
    displayName: "Testing"
    pool:
      name: Azure Pipelines
      vmImage: "windows-2019"
      demands: npm
    
    steps:
    - task: DotNetCoreCLI@2
      inputs:
        command: test
        projects: '**/*Tests/*.csproj'
        arguments: '--configuration Release'

- stage: 'Publish'
  displayName: 'Publish to Marketplace'
  dependsOn: Test
  jobs:
  - job: Publish
    displayName: "Publish"
    pool:
      name: Azure Pipelines
      vmImage: "windows-2019"
      demands: npm

    steps:
    - task: DownloadBuildArtifacts@1
      inputs:
        buildType: 'current'
        downloadType: 'single'
        artifactName: 'vsix'
        downloadPath: '$(System.ArtifactsDirectory)'
    - task: NodeTool@0
      inputs:
        versionSpec: '10.x'
          
    - task: TfxInstaller@3
      inputs:
        version: 'v0.9.x'

    - task: PublishAzureDevOpsExtension@3
      inputs:
        connectTo: 'VsTeam'
        connectedServiceName: 'Visual Studio Marketplace Service Connection'
        fileType: 'vsix'
        vsixFile: '$(Build.ArtifactStagingDirectory)/vsix/*.vsix'
  